# Imagecache reflect module schema: imagecache_reflect.schema.yml

# Image effects plugins: image.effect.%
# These are used in image styles.
image.effect.imagecache_reflect:
  type: mapping
  label: 'Imagecache reflect'
  mapping:
    bgcolor:
      label: 'Background color'
    transparency:
      type: boolean
      label: 'Transparent source image'
    position:
      label: 'Position'
    size:
      label: 'Size'
